-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity matmul is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    bram_0_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    bram_0_EN_A : OUT STD_LOGIC;
    bram_0_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
    bram_0_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    bram_0_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
    bram_0_Clk_A : OUT STD_LOGIC;
    bram_0_Rst_A : OUT STD_LOGIC;
    bram_1_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    bram_1_EN_A : OUT STD_LOGIC;
    bram_1_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
    bram_1_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    bram_1_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
    bram_1_Clk_A : OUT STD_LOGIC;
    bram_1_Rst_A : OUT STD_LOGIC;
    bram_2_Addr_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    bram_2_EN_A : OUT STD_LOGIC;
    bram_2_WEN_A : OUT STD_LOGIC_VECTOR (3 downto 0);
    bram_2_Din_A : OUT STD_LOGIC_VECTOR (31 downto 0);
    bram_2_Dout_A : IN STD_LOGIC_VECTOR (31 downto 0);
    bram_2_Clk_A : OUT STD_LOGIC;
    bram_2_Rst_A : OUT STD_LOGIC;
    values : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of matmul is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "matmul_matmul,hls_ip_2023_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.912000,HLS_SYN_LAT=1319041,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=367,HLS_SYN_LUT=269,HLS_VERSION=2023_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal add_ln16_fu_155_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln16_reg_252 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal empty_fu_161_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal empty_reg_257 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln16_fu_149_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln17_fu_171_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln17_reg_266 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal trunc_ln18_fu_177_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln18_reg_271 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln17_fu_165_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bram_2_addr_reg_276 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln19_fu_203_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln19_reg_284 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal icmp_ln19_fu_197_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bram_0_load_reg_299 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal bram_1_load_reg_304 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_137_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln20_reg_309 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal add_ln20_fu_237_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal j_reg_102 : STD_LOGIC_VECTOR (6 downto 0);
    signal k_reg_113 : STD_LOGIC_VECTOR (6 downto 0);
    signal add304_reg_124 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln18_fu_188_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln20_fu_220_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln20_1_fu_232_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_fu_60 : STD_LOGIC_VECTOR (6 downto 0);
    signal bram_0_Addr_A_orig : STD_LOGIC_VECTOR (31 downto 0);
    signal bram_1_Addr_A_orig : STD_LOGIC_VECTOR (31 downto 0);
    signal bram_2_Addr_A_orig : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal add_ln_fu_181_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln20_fu_209_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln1_fu_213_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln20_1_fu_225_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component matmul_mul_32s_32s_32_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    mul_32s_32s_32_2_1_U1 : component matmul_mul_32s_32s_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => bram_1_load_reg_304,
        din1 => bram_0_load_reg_299,
        ce => ap_const_logic_1,
        dout => grp_fu_137_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    add304_reg_124_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln17_fu_165_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                add304_reg_124 <= ap_const_lv32_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                add304_reg_124 <= add_ln20_fu_237_p2;
            end if; 
        end if;
    end process;

    i_fu_60_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                i_fu_60 <= ap_const_lv7_0;
            elsif (((icmp_ln17_fu_165_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                i_fu_60 <= add_ln16_reg_252;
            end if; 
        end if;
    end process;

    j_reg_102_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln16_fu_149_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                j_reg_102 <= ap_const_lv7_0;
            elsif (((icmp_ln19_fu_197_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                j_reg_102 <= add_ln17_reg_266;
            end if; 
        end if;
    end process;

    k_reg_113_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln17_fu_165_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                k_reg_113 <= ap_const_lv7_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                k_reg_113 <= add_ln19_reg_284;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                add_ln16_reg_252 <= add_ln16_fu_155_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                add_ln17_reg_266 <= add_ln17_fu_171_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                add_ln19_reg_284 <= add_ln19_fu_203_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                bram_0_load_reg_299 <= bram_0_Dout_A;
                bram_1_load_reg_304 <= bram_1_Dout_A;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln17_fu_165_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                bram_2_addr_reg_276 <= zext_ln18_fu_188_p1(12 - 1 downto 0);
                trunc_ln18_reg_271 <= trunc_ln18_fu_177_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln16_fu_149_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                empty_reg_257 <= empty_fu_161_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                mul_ln20_reg_309 <= grp_fu_137_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln16_fu_149_p2, ap_CS_fsm_state3, icmp_ln17_fu_165_p2, ap_CS_fsm_state4, icmp_ln19_fu_197_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln16_fu_149_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((icmp_ln17_fu_165_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                if (((icmp_ln19_fu_197_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when others =>  
                ap_NS_fsm <= "XXXXXXXX";
        end case;
    end process;
    add_ln16_fu_155_p2 <= std_logic_vector(unsigned(i_fu_60) + unsigned(ap_const_lv7_1));
    add_ln17_fu_171_p2 <= std_logic_vector(unsigned(j_reg_102) + unsigned(ap_const_lv7_1));
    add_ln19_fu_203_p2 <= std_logic_vector(unsigned(k_reg_113) + unsigned(ap_const_lv7_1));
    add_ln1_fu_213_p3 <= (empty_reg_257 & trunc_ln20_fu_209_p1);
    add_ln20_1_fu_225_p3 <= (trunc_ln20_fu_209_p1 & trunc_ln18_reg_271);
    add_ln20_fu_237_p2 <= std_logic_vector(unsigned(mul_ln20_reg_309) + unsigned(add304_reg_124));
    add_ln_fu_181_p3 <= (empty_reg_257 & trunc_ln18_fu_177_p1);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_CS_fsm_state2, icmp_ln16_fu_149_p2)
    begin
        if (((icmp_ln16_fu_149_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln16_fu_149_p2)
    begin
        if (((icmp_ln16_fu_149_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    bram_0_Addr_A <= std_logic_vector(shift_left(unsigned(bram_0_Addr_A_orig),to_integer(unsigned('0' & ap_const_lv32_2(31-1 downto 0)))));
    bram_0_Addr_A_orig <= zext_ln20_fu_220_p1(32 - 1 downto 0);
    bram_0_Clk_A <= ap_clk;
    bram_0_Din_A <= ap_const_lv32_0;

    bram_0_EN_A_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            bram_0_EN_A <= ap_const_logic_1;
        else 
            bram_0_EN_A <= ap_const_logic_0;
        end if; 
    end process;

    bram_0_Rst_A <= ap_rst_n_inv;
    bram_0_WEN_A <= ap_const_lv4_0;
    bram_1_Addr_A <= std_logic_vector(shift_left(unsigned(bram_1_Addr_A_orig),to_integer(unsigned('0' & ap_const_lv32_2(31-1 downto 0)))));
    bram_1_Addr_A_orig <= zext_ln20_1_fu_232_p1(32 - 1 downto 0);
    bram_1_Clk_A <= ap_clk;
    bram_1_Din_A <= ap_const_lv32_0;

    bram_1_EN_A_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            bram_1_EN_A <= ap_const_logic_1;
        else 
            bram_1_EN_A <= ap_const_logic_0;
        end if; 
    end process;

    bram_1_Rst_A <= ap_rst_n_inv;
    bram_1_WEN_A <= ap_const_lv4_0;
    bram_2_Addr_A <= std_logic_vector(shift_left(unsigned(bram_2_Addr_A_orig),to_integer(unsigned('0' & ap_const_lv32_2(31-1 downto 0)))));
    bram_2_Addr_A_orig <= std_logic_vector(IEEE.numeric_std.resize(unsigned(bram_2_addr_reg_276),32));
    bram_2_Clk_A <= ap_clk;
    bram_2_Din_A <= add304_reg_124;

    bram_2_EN_A_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            bram_2_EN_A <= ap_const_logic_1;
        else 
            bram_2_EN_A <= ap_const_logic_0;
        end if; 
    end process;

    bram_2_Rst_A <= ap_rst_n_inv;

    bram_2_WEN_A_assign_proc : process(ap_CS_fsm_state4, icmp_ln19_fu_197_p2)
    begin
        if (((icmp_ln19_fu_197_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            bram_2_WEN_A <= ap_const_lv4_F;
        else 
            bram_2_WEN_A <= ap_const_lv4_0;
        end if; 
    end process;

    empty_fu_161_p1 <= i_fu_60(6 - 1 downto 0);
    icmp_ln16_fu_149_p2 <= "1" when (i_fu_60 = ap_const_lv7_40) else "0";
    icmp_ln17_fu_165_p2 <= "1" when (j_reg_102 = ap_const_lv7_40) else "0";
    icmp_ln19_fu_197_p2 <= "1" when (k_reg_113 = ap_const_lv7_40) else "0";
    trunc_ln18_fu_177_p1 <= j_reg_102(6 - 1 downto 0);
    trunc_ln20_fu_209_p1 <= k_reg_113(6 - 1 downto 0);
    zext_ln18_fu_188_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln_fu_181_p3),64));
    zext_ln20_1_fu_232_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln20_1_fu_225_p3),64));
    zext_ln20_fu_220_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln1_fu_213_p3),64));
end behav;
